version: "2.4"

services:
  odoo:
    build:
      context: ./odoo
      args:
        ODOO_VERSION: "14.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    environment:
      EMAIL_FROM: ""
      PGDATABASE: &dbname prod
      PGUSER: &dbuser "odoo"
      DB_SOURCE: "odoo_v13"
      DB_TARGET: "odoo_v14"
      PROXY_MODE: "false"
      LIST_DB: "false"
    tty: true
    volumes:
      - filestore:/var/lib/odoo:z

  db:
    image: postgres:12-alpine
    shm_size: 4gb
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: odoopassword
      POSTGRES_USER: *dbuser
      CONF_EXTRA: |
        work_mem = 512MB
    volumes:
      - db:/var/lib/postgresql/data:z

  smtpfake:
    image: mailhog/mailhog
