version: "2.4"

services:
  odoo:
    build:
      context: ./odoo
      args:
        ODOO_VERSION: "13.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    environment:
      EMAIL_FROM: ""
      DB_SOURCE: "odoo_v12"
      DB_TARGET: "odoo_v13"
      PGDATABASE: &dbname "odoo_v13"
      PGUSER: &dbuser "odoo"
      DB_FILTER: ".*"
      PROXY_MODE: "false"
    tty: true
    volumes:
      - ~/odoo_v11_data:/var/lib/odoo_old:z
      - ~/odoo_v12_data:/var/lib/odoo:z

  db:
    image: postgres:9.6-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: odoopassword
      POSTGRES_USER: *dbuser
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200", "-c", "max_wal_size=4GB"]
    volumes:
    - ~/postgresql_data/:/var/lib/postgresql/data/:z

  smtpfake:
    image: mailhog/mailhog