version: "3.3"

services:

  postgresql:
    image: postgres:9.6-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: odoopassword
      POSTGRES_USER: odoo
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200", "-c", "max_wal_size=4GB"]
    volumes:
    - ~/postgresql_data/:/var/lib/postgresql/data/

  # This is your original Odoo v8 deploy.
  # Use this as a reference for changes that need to be made in other sections
  # in order to match your actual deploy. An environment file makes this easier,
  # but was excluded in the interest of a one file example.
  #
  # odoo_v8:
  #  image: your_organization/your_odoo_scaffold_image:8.0
  #  environment:
  #    - PGDATABASE: odoo_v8
  #    - PGPASSWORD: odoo_password
  #    - PGUSER: odoo_user
  #  volumes:
  #    - ~/odoo_v8_data:/var/lib/odoo
  #  links:
  #    - postgresql:db

  horizon_v10:
    image: be-cloud/horizon-upgrade:10.0-up
    volumes:
      - ~/odoo_v9_data:/var/lib/odoo_old
      - ~/odoo_v10_data:/var/lib/odoo
    environment:
      DB_SOURCE: odoo_v9
      DB_TARGET: odoo_v10
      PGDATABASE: odoo_v10
      PGUSER: odoo
      PGPASSWORD: odoopassword
      # ODOO_BACKUP_PATH : ~/backup_local.zip
    links:
      - postgresql:db
      - postgresql:db_old