version: "3.3"

services:

  postgresql:
    image: postgres:9.6-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: odoopassword
      POSTGRES_USER: odoo
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200", "-c", "max_wal_size=4GB"]
    volumes:
    - ~/postgresql_data/:/var/lib/postgresql/data/

  odoo_v11:
    image: be-cloud/horizon-upgrade:11.0
    ports:
      - "80:8069"
    volumes:
      - ~/odoo_v11_data:/var/lib/odoo
    environment:
      DB_SOURCE: odoo_v11
      PGUSER: odoo
      PGPASSWORD: odoopassword
    links:
      - postgresql:db
      