version: "3.3"

services:

  postgresql:
    image: postgres:9.6-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoopassword
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200", "-c", "max_wal_size=4GB"]
    volumes:
    - ~/postgresql_data/:/var/lib/postgresql/data/

  odoo_v9:
    image: be-cloud/horizon-upgrade:9.0
    volumes:
      - ~/odoo_v9_data:/var/lib/odoo
    environment:
      DB_SOURCE: odoo_v9
      PGUSER: odoo
      PGPASSWORD: odoopassword
    links:
      - postgresql:db