version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    ports:
      - "6899:6899"
      - "80:8069"
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "en_US"
      LIST_DB: "true"
      PGDATABASE: &dbname odoo_v14
      PYTHONPATH: /opt/odoo/custom/src/odoo
      SMTP_PORT: "1025"
      WDB_WEB_PORT: "14984"
    volumes:
      - ./odoo/custom:/opt/odoo/custom:ro,z
      - ./odoo/auto:/opt/odoo/auto:rw,z
    depends_on:
      - db
    networks:
      default:
    labels:
      doodba.domain.main: "horizon-dev.student-crlg.be"
    command:
      - odoo

  db:
    extends:
      file: common.yaml
      service: db
    environment:
      POSTGRES_DB: *dbname
      POSTGRES_PASSWORD: odoopassword
    restart: unless-stopped

networks:
  default:
    driver_opts:
      encrypted: 1

volumes:
  filestore:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/odoo_v14_data
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/postgresql_data
